language: node_js

node_js:
  - "4"
  - "6"
  - "8"

sudo: false

before_script:
 - npm install dat-registry-api

script:
 - npm test

notifications:
  irc:
    channels:
      - "chat.freenode.net#datbots"
    template:
      - "%{repository_slug} - %{commit_subject} - %{result} - %{build_url}"
    skip_join: true
    on_success: change
    on_failure: always

