language: node_js

node_js:
 - "0.12"

branches:
  except:
    - beta

# Using faster container based build environment.

sudo: false

before_script:
 - npm install -g npm

script:
 - npm test
 
notifications:
  irc:
    channels:
      - "chat.freenode.net#dat"
    template:
      - "%{repository_slug} - %{commit_subject} - %{result} - %{build_url}"
    skip_join: true
    on_success: change
    on_failure: always
    