environment:
  matrix:
    - nodejs_version: '5'
    - nodejs_version: '4'
    - nodejs_version: '0.12'
    - nodejs_version: '0.10'
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
build: off
shallow_clone: true
clone_depth: 1
test_script:
  - node --version
  - npm --version
  - npm test
