site_name: Dat Project CLI
theme: readthedocs
pages:
- "Introduction": 'index.md'
- "Getting Started": 'usage.md'
- "Full Usage": 'api.md'
- Meta:
  - 'Changelog': 'meta/changelog.md'
  - 'Collaborators': 'meta/collaborators.md'
extra_css: [assets/extra.css]
